spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #https://stackoverflow.com/questions/7605953/how-to-change-mysql-timezone-in-java-connection 关于时区的配置
    url: jdbc:mysql://127.0.0.1:8066/miners_mall?&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: root
    password: ''
    #type: com.zaxxer.hikari.HikariDataSource
    hikari:
    #  minimum-idle: 5
    #  maximum-pool-size: 40
    #  connection-test-query: SELECT 1

  #redis:
   # host: 
   # database: 3
    #port: 8077
    #password: ''
   # jedis.pool:
    #  max-idle: 50
    #  max-active: 200
     # max-wait: 1000


  redis:
    host: 127.0.0.1
    database: 3
    port: 6379
    password: ''
    jedis.pool:
      max-idle: 50
      max-active: 200
      max-wait: 1000

sms:
  url: 
  account: 
  passwd: 
  ignore: true #不校验短信验证码
  tplId:

email:
  serverHost: 
  serverPort: 
  userName: 
  userPassword:
  fromAddress: 
  validate: true

########################## log ##########################
logging:
  config: classpath:config/log/log.xml
  file: ./logs/api.log
