spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #https://blog.csdn.net/qq631431929/article/details/51731834
    url: jdbc:mysql://47.74.145.76:8066/miners_house?&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: root
    password: '%TGBHU*nm123'

  redis:
    host: 47.74.145.76
    database: 0
    port: 8079
    password: '2wsx#EDC$RFV'
    jedis.pool:
      max-idle: 50
      max-active: 200
      max-wait: 1000

sms:
  url:
  account:
  passwd:

########################## log ##########################
logging:
  config: classpath:config/log/log.xml
  file: ./logs/admin.log

########################### 融云 ###########################
rongHub:
  appKey: 8w7jv4qb8204y
  appSecret: pAY7dOPTR3